### ISSUE TITLE
Dashboard container not launched

### ISSUE THREAD

**Issue by arkocal** [Open-IoT-Service-Platform/platform-launcher#34]
I tried running `make start` on commit bebc3851e9029e2e63de13c17f4e2176a4cf0ad9 (latest on development branch as of now). The command runs silently, but `docker ps` reveals that the container `platformlauncher_dashboard_1` is not started. Here is the output from `docker logs dashboard_launcher_1`:

```
2018-04-09T14:04:53.314Z - error: uncaughtException: Cannot read property 'name' of undefined date=Mon Apr 09 2018 14:04:53 GMT+0000 (UTC), pid=56, uid=0, gid=0, cwd=/app, execPath=/usr/local/bin/node, version=v4.8.3, argv=[/usr/local/bin/node, /app/app.js], rss=106729472, heapTotal=85920352, heapUsed=62743960, external=1482695, loadavg=[2.88720703125, 2.5869140625, 2.3681640625], uptime=20893, trace=[column=55, file=/app/lib/heartbeat.js, function=Object.exports.start, line=48, method=start, native=false, column=39, file=/app/app.js, function=null, line=139, method=null, native=false, column=16, file=events.js, function=Server.g, line=260, method=g, native=false, column=20, file=events.js, function=emitNone, line=72, method=null, native=false, column=7, file=events.js, function=Server.emit, line=166, method=emit, native=false, column=10, file=net.js, function=emitListeningNT, line=1279, method=null, native=false, column=9, file=node.js, function=nextTickCallbackWith1Arg, line=500, method=null, native=false, column=17, file=node.js, function=process._tickCallback, line=422, method=_tickCallback, native=false], stack=[TypeError: Cannot read property 'name' of undefined,     at Object.exports.start (/app/lib/heartbeat.js:48:55),     at Server.<anonymous> (/app/app.js:139:39),     at Server.g (events.js:260:16),     at emitNone (events.js:72:20),     at Server.emit (events.js:166:7),     at emitListeningNT (net.js:1279:10),     at nextTickCallbackWith1Arg (node.js:500:9),     at process._tickCallback (node.js:422:17)]
```

I have changed line 48 in `app/lib/hearbeat.js` to  
`var topic = config.drsProxy.kafka.topics.heartbeat;` and this resolved the issue on my system, but I am not sure whether this breaks something else.

**Comment by arkocal** [comment]
Apparently, the config scripts need to be rerun after the update, maybe we should include this in the Makefile?

**Comment by arkocal** [comment]
After a clean install I am getting this error:
```
2018-04-12T13:52:56.797Z - error: uncaughtException: Could not locate the bindings file. Tried:
 → /app/node_modules/jsjws/node_modules/ursa/build/ursaNative.node
 → /app/node_modules/jsjws/node_modules/ursa/build/Debug/ursaNative.node
 → /app/node_modules/jsjws/node_modules/ursa/build/Release/ursaNative.node
 → /app/node_modules/jsjws/node_modules/ursa/out/Debug/ursaNative.node
 → /app/node_modules/jsjws/node_modules/ursa/Debug/ursaNative.node
 → /app/node_modules/jsjws/node_modules/ursa/out/Release/ursaNative.node
 → /app/node_modules/jsjws/node_modules/ursa/Release/ursaNative.node
 → /app/node_modules/jsjws/node_modules/ursa/build/default/ursaNative.node
 → /app/node_modules/jsjws/node_modules/ursa/compiled/4.8.3/linux/x64/ursaNative.node date=Thu Apr 12 2018 13:52:56 GMT+0000 (UTC), pid=55, uid=0, gid=0, cwd=/app, execPath=/usr/local/bin/node, version=v4.8.3, argv=[/usr/local/bin/node, /app/app.js], rss=41676800, heapTotal=31131232, heapUsed=16914904, external=523504, loadavg=[5.58154296875, 3.03662109375, 1.9833984375], uptime=15416, trace=[column=9, file=/app/node_modules/jsjws/node_modules/ursa/node_modules/bindings/bindings.js, function=bindings, line=93, method=null, native=false, column=37, file=/app/node_modules/jsjws/node_modules/ursa/lib/ursa.js, function=null, line=18, method=null, native=false, column=26, file=module.js, function=Module._compile, line=409, method=_compile, native=false, column=10, file=module.js, function=Module._extensions..js, line=416, method=.js, native=false, column=32, file=module.js, function=Module.load, line=343, method=load, native=false, column=12, file=module.js, function=Module._load, line=300, method=_load, native=false, column=17, file=module.js, function=Module.require, line=353, method=require, native=false, column=17, file=internal/module.js, function=require, line=12, method=null, native=false, column=12, file=/app/node_modules/jsjws/lib/jsjws.js, function=null, line=14141, method=null, native=false, column=26, file=module.js, function=Module._compile, line=409, method=_compile, native=false], stack=[Error: Could not locate the bindings file. Tried:,  → /app/node_modules/jsjws/node_modules/ursa/build/ursaNative.node,  → /app/node_modules/jsjws/node_modules/ursa/build/Debug/ursaNative.node,  → /app/node_modules/jsjws/node_modules/ursa/build/Release/ursaNative.node,  → /app/node_modules/jsjws/node_modules/ursa/out/Debug/ursaNative.node,  → /app/node_modules/jsjws/node_modules/ursa/Debug/ursaNative.node,  → /app/node_modules/jsjws/node_modules/ursa/out/Release/ursaNative.node,  → /app/node_modules/jsjws/node_modules/ursa/Release/ursaNative.node,  → /app/node_modules/jsjws/node_modules/ursa/build/default/ursaNative.node,  → /app/node_modules/jsjws/node_modules/ursa/compiled/4.8.3/linux/x64/ursaNative.node,     at bindings (/app/node_modules/jsjws/node_modules/ursa/node_modules/bindings/bindings.js:93:9),     at Object.<anonymous> (/app/node_modules/jsjws/node_modules/ursa/lib/ursa.js:18:37),     at Module._compile (module.js:409:26),     at Object.Module._extensions..js (module.js:416:10),     at Module.load (module.js:343:32),     at Function.Module._load (module.js:300:12),     at Module.require (module.js:353:17),     at require (internal/module.js:12:17),     at Object.<anonymous> (/app/node_modules/jsjws/lib/jsjws.js:14141:12),     at Module._compile (module.js:409:26)]
```
