### ISSUE TITLE
Kafka cluster deployment fails: intermittent issue

### ISSUE THREAD

**Issue by yshashix** [Open-IoT-Service-Platform/platform-launcher#712]
- my-cluster-kafka pods in crashLoopback

Similar to issue [https://github.com/strimzi/strimzi-kafka-operator/discussions/6893](url)

-> Fixed by increasing resources size from 100m -> 200m

**Comment by yshashix** [comment]
Operator logs:

```
`2023-03-08 09:40:09 INFO  ClusterOperator:105 - Opened watch for KafkaMirrorMaker2 operator
2023-03-08 09:40:09 INFO  ClusterOperator:117 - Setting up periodic reconciliation for namespace iff
2023-03-08 09:40:09 INFO  Main:203 - Cluster Operator verticle started in namespace iff without label selector
2023-03-08 09:42:09 INFO  ClusterOperator:120 - Triggering periodic reconciliation for namespace iff
2023-03-08 09:42:09 WARN  VersionUsageUtils:60 - The client is using resource type 'kafkamirrormakers' with unstable version 'v1beta2'
2023-03-08 09:42:09 WARN  VersionUsageUtils:60 - The client is using resource type 'kafkaconnects' with unstable version 'v1beta2'
2023-03-08 09:42:09 WARN  VersionUsageUtils:60 - The client is using resource type 'kafkamirrormaker2s' with unstable version 'v1beta2'
2023-03-08 09:42:09 WARN  VersionUsageUtils:60 - The client is using resource type 'kafkabridges' with unstable version 'v1beta2'
2023-03-08 09:42:09 WARN  VersionUsageUtils:60 - The client is using resource type 'kafkarebalances' with unstable version 'v1beta2'
2023-03-08 09:42:09 WARN  VersionUsageUtils:60 - The client is using resource type 'kafkaconnectors' with unstable version 'v1beta2'
2023-03-08 09:44:09 INFO  ClusterOperator:120 - Triggering periodic reconciliation for namespace iff
2023-03-08 09:44:33 INFO  AbstractConnectOperator:228 - Reconciliation #3(connector-watch) KafkaConnect(iff/kafka-connect): KafkaConnector entity-table-connector in namespace iff was ADDED
2023-03-08 09:44:33 INFO  OperatorWatcher:38 - Reconciliation #1(watch) Kafka(iff/my-cluster): Kafka my-cluster in namespace iff was ADDED
2023-03-08 09:44:33 INFO  OperatorWatcher:38 - Reconciliation #2(watch) KafkaConnect(iff/kafka-connect): KafkaConnect kafka-connect in namespace iff was ADDED
2023-03-08 09:44:33 INFO  AbstractConnectOperator:469 - Reconciliation #3(connector-watch) KafkaConnect(iff/kafka-connect): creating/updating connector: entity-table-connector
2023-03-08 09:44:34 INFO  AbstractOperator:237 - Reconciliation #1(watch) Kafka(iff/my-cluster): Kafka my-cluster will be checked for creation or modification
2023-03-08 09:44:34 INFO  CrdOperator:111 - Reconciliation #1(watch) Kafka(iff/my-cluster): Status of Kafka my-cluster in namespace iff has been updated
2023-03-08 09:44:34 INFO  OperatorWatcher:38 - Reconciliation #4(watch) Kafka(iff/my-cluster): Kafka my-cluster in namespace iff was MODIFIED
2023-03-08 09:44:34 WARN  AbstractConnectOperator:732 - Reconciliation #3(connector-watch) KafkaConnect(iff/kafka-connect): Error reconciling connector entity-table-connector
java.net.UnknownHostException: Failed to resolve 'kafka-connect-connect-api.iff.svc' after 2 queries
        at io.netty.resolver.dns.DnsResolveContext.finishResolve(DnsResolveContext.java:1047) ~[io.netty.netty-resolver-dns-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.resolver.dns.DnsResolveContext.tryToFinishResolve(DnsResolveContext.java:1000) ~[io.netty.netty-resolver-dns-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.resolver.dns.DnsResolveContext.query(DnsResolveContext.java:418) ~[io.netty.netty-resolver-dns-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.resolver.dns.DnsResolveContext.onResponse(DnsResolveContext.java:629) ~[io.netty.netty-resolver-dns-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.resolver.dns.DnsResolveContext.access$400(DnsResolveContext.java:66) ~[io.netty.netty-resolver-dns-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.resolver.dns.DnsResolveContext$2.operationComplete(DnsResolveContext.java:462) ~[io.netty.netty-resolver-dns-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListener0(DefaultPromise.java:578) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners0(DefaultPromise.java:571) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListenersNow(DefaultPromise.java:550) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.concurrent.DefaultPromise.notifyListeners(DefaultPromise.java:491) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.concurrent.DefaultPromise.setValue0(DefaultPromise.java:616) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.concurrent.DefaultPromise.setSuccess0(DefaultPromise.java:605) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.concurrent.DefaultPromise.trySuccess(DefaultPromise.java:104) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.resolver.dns.DnsQueryContext.trySuccess(DnsQueryContext.java:216) ~[io.netty.netty-resolver-dns-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.resolver.dns.DnsQueryContext.finish(DnsQueryContext.java:208) ~[io.netty.netty-resolver-dns-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.resolver.dns.DnsNameResolver$DnsResponseHandler.channelRead(DnsNameResolver.java:1314) ~[io.netty.netty-resolver-dns-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[io.netty.netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[io.netty.netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[io.netty.netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.handler.codec.MessageToMessageDecoder.channelRead(MessageToMessageDecoder.java:103) ~[io.netty.netty-codec-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[io.netty.netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[io.netty.netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.fireChannelRead(AbstractChannelHandlerContext.java:357) ~[io.netty.netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.DefaultChannelPipeline$HeadContext.channelRead(DefaultChannelPipeline.java:1410) ~[io.netty.netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:379) ~[io.netty.netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:365) ~[io.netty.netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.DefaultChannelPipeline.fireChannelRead(DefaultChannelPipeline.java:919) ~[io.netty.netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.nio.AbstractNioMessageChannel$NioMessageUnsafe.read(AbstractNioMessageChannel.java:97) ~[io.netty.netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKey(NioEventLoop.java:722) ~[io.netty.netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeysOptimized(NioEventLoop.java:658) ~[io.netty.netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.nio.NioEventLoop.processSelectedKeys(NioEventLoop.java:584) ~[io.netty.netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.channel.nio.NioEventLoop.run(NioEventLoop.java:496) ~[io.netty.netty-transport-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$4.run(SingleThreadEventExecutor.java:995) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.internal.ThreadExecutorMap$2.run(ThreadExecutorMap.java:74) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) ~[io.netty.netty-common-4.1.77.Final.jar:4.1.77.Final]
        at java.lang.Thread.run(Thread.java:829) ~[?:?]
2023-03-08 09:44:34 INFO  CrdOperator:111 - Reconciliation #3(connector-watch) KafkaConnect(iff/kafka-connect): Status of KafkaConnector entity-table-connector in namespace iff has been updated
2023-03-08 09:44:34 INFO  Ca:994 - Reconciliation #1(watch) Kafka(iff/my-cluster): Generating CA with subject=Subject(organizationName='io.strimzi', commonName='cluster-ca v0', dnsNames=[], ipAddresses=[])
2023-03-08 09:44:34 INFO  AbstractConnectOperator:236 - Reconciliation #3(connector-watch) KafkaConnect(iff/kafka-connect): reconciled
2023-03-08 09:44:34 INFO  AbstractConnectOperator:228 - Reconciliation #5(connector-watch) KafkaConnect(iff/kafka-connect): KafkaConnector entity-table-connector in namespace iff was MODIFIED
2023-03-08 09:44:34 INFO  AbstractOperator:237 - Reconciliation #2(watch) KafkaConnect(iff/kafka-connect): KafkaConnect kafka-connect will be checked for creation or modification
2023-03-08 09:44:35 INFO  Ca:994 - Reconciliation #1(watch) Kafka(iff/my-cluster): Generating CA with subject=Subject(organizationName='io.strimzi', commonName='clients-ca v0', dnsNames=[], ipAddresses=[])
2023-03-08 09:44:35 INFO  Ca:290 - Reconciliation #1(watch) Kafka(iff/my-cluster): Generating certificate Subject(organizationName='io.strimzi', commonName='cluster-operator', dnsNames=[], ipAddresses=[]), signed by CA cluster-ca
2023-03-08 09:44:36 INFO  Ca:290 - Reconciliation #1(watch) Kafka(iff/my-cluster): Generating certificate Subject(organizationName='io.strimzi', commonName='my-cluster-zookeeper', dnsNames=[my-cluster-zookeeper-0.my-cluster-zookeeper-nodes.iff.svc.cluster.local, *.my-cluster-zookeeper-nodes.iff.svc, *.my-cluster-zookeeper-client.iff.svc.cluster.local, my-cluster-zookeeper-client.iff.svc.cluster.local, my-cluster-zookeeper-0.my-cluster-zookeeper-nodes.iff.svc, my-cluster-zookeeper-client.iff.svc, *.my-cluster-zookeeper-client.iff.svc, *.my-cluster-zookeeper-nodes.iff.svc.cluster.local, my-cluster-zookeeper-client.iff, my-cluster-zookeeper-client], ipAddresses=[]), signed by CA cluster-ca
2023-03-08 09:44:36 INFO  StrimziPodSetController:292 - Reconciliation #6(watch) StrimziPodSet(iff/my-cluster-zookeeper): StrimziPodSet will be reconciled
2023-03-08 09:44:36 INFO  StrimziPodSetController:328 - Reconciliation #6(watch) StrimziPodSet(iff/my-cluster-zookeeper): reconciled
2023-03-08 09:44:36 INFO  StrimziPodSetController:292 - Reconciliation #7(watch) StrimziPodSet(iff/my-cluster-zookeeper): StrimziPodSet will be reconciled
2023-03-08 09:44:36 INFO  StrimziPodSetController:328 - Reconciliation #7(watch) StrimziPodSet(iff/my-cluster-zookeeper): reconciled
2023-03-08 09:44:36 INFO  StrimziPodSetController:292 - Reconciliation #8(watch) StrimziPodSet(iff/my-cluster-zookeeper): StrimziPodSet will be reconciled
2023-03-08 09:44:36 INFO  StrimziPodSetController:328 - Reconciliation #8(watch) StrimziPodSet(iff/my-cluster-zookeeper): reconciled
2023-03-08 09:44:40 INFO  StrimziPodSetController:292 - Reconciliation #9(watch) StrimziPodSet(iff/my-cluster-zookeeper): StrimziPodSet will be reconciled
2023-03-08 09:44:40 INFO  StrimziPodSetController:328 - Reconciliation #9(watch) StrimziPodSet(iff/my-cluster-zookeeper): reconciled
2023-03-08 09:44:40 INFO  StrimziPodSetController:292 - Reconciliation #10(watch) StrimziPodSet(iff/my-cluster-zookeeper): StrimziPodSet will be reconciled
2023-03-08 09:44:40 INFO  StrimziPodSetController:328 - Reconciliation #10(watch) StrimziPodSet(iff/my-cluster-zookeeper): reconciled
2023-03-08 09:45:34 INFO  AbstractOperator:378 - Reconciliation #1(watch) Kafka(iff/my-cluster): Reconciliation is in progress
2023-03-08 09:45:34 INFO  AbstractOperator:378 - Reconciliation #2(watch) KafkaConnect(iff/kafka-connect): Reconciliation is in progress
2023-03-08 09:46:09 INFO  ClusterOperator:120 - Triggering periodic reconciliation for namespace iff
2023-03-08 09:46:31 INFO  StrimziPodSetController:292 - Reconciliation #13(watch) StrimziPodSet(iff/my-cluster-zookeeper): StrimziPodSet will be reconciled
2023-03-08 09:46:31 INFO  StrimziPodSetController:328 - Reconciliation #13(watch) StrimziPodSet(iff/my-cluster-zookeeper): reconciled
2023-03-08 09:46:34 INFO  AbstractOperator:378 - Reconciliation #1(watch) Kafka(iff/my-cluster): Reconciliation is in progress
2023-03-08 09:46:34 INFO  AbstractOperator:378 - Reconciliation #2(watch) KafkaConnect(iff/kafka-connect): Reconciliation is in progress
2023-03-08 09:47:02 INFO  StrimziPodSetController:292 - Reconciliation #14(watch) StrimziPodSet(iff/my-cluster-zookeeper): StrimziPodSet will be reconciled
2023-03-08 09:47:02 INFO  StrimziPodSetController:328 - Reconciliation #14(watch) StrimziPodSet(iff/my-cluster-zookeeper): reconciled
2023-03-08 09:47:02 INFO  StrimziPodSetController:292 - Reconciliation #15(watch) StrimziPodSet(iff/my-cluster-zookeeper): StrimziPodSet will be reconciled
2023-03-08 09:47:02 INFO  StrimziPodSetController:328 - Reconciliation #15(watch) StrimziPodSet(iff/my-cluster-zookeeper): reconciled
2023-03-08 09:47:12 WARN  ClientCnxn:1257 - Client session timed out, have not heard from server in 10000ms for session id 0x0
2023-03-08 09:47:12 WARN  ClientCnxn:1300 - Session 0x0 for sever my-cluster-zookeeper-0.my-cluster-zookeeper-nodes.iff.svc/10.42.0.19:2181, Closing socket connection. Attempting reconnect except it is a SessionExpiredException.
org.apache.zookeeper.ClientCnxn$SessionTimeoutException: Client session timed out, have not heard from server in 10000ms for session id 0x0
        at org.apache.zookeeper.ClientCnxn$SendThread.run(ClientCnxn.java:1258) ~[org.apache.zookeeper.zookeeper-3.6.3.jar:3.6.3]
2023-03-08 09:47:23 INFO  Ca:290 - Reconciliation #1(watch) Kafka(iff/my-cluster): Generating certificate Subject(organizationName='io.strimzi', commonName='my-cluster-kafka', dnsNames=[my-cluster-kafka-brokers.iff.svc.cluster.local, my-cluster-kafka-0.my-cluster-kafka-brokers.iff.svc.cluster.local, my-cluster-kafka-0.my-cluster-kafka-brokers.iff.svc, my-cluster-kafka-bootstrap.iff, my-cluster-kafka-bootstrap.iff.svc.cluster.local, my-cluster-kafka-brokers, my-cluster-kafka-brokers.iff.svc, my-cluster-kafka-brokers.iff, my-cluster-kafka-bootstrap.iff.svc, my-cluster-kafka-bootstrap], ipAddresses=[]), signed by CA cluster-ca
2023-03-08 09:47:23 INFO  StrimziPodSetController:292 - Reconciliation #16(watch) StrimziPodSet(iff/my-cluster-kafka): StrimziPodSet will be reconciled
2023-03-08 09:47:23 INFO  StrimziPodSetController:328 - Reconciliation #16(watch) StrimziPodSet(iff/my-cluster-kafka): reconciled
2023-03-08 09:47:23 INFO  StrimziPodSetController:292 - Reconciliation #17(watch) StrimziPodSet(iff/my-cluster-kafka): StrimziPodSet will be reconciled
2023-03-08 09:47:23 INFO  StrimziPodSetController:328 - Reconciliation #17(watch) StrimziPodSet(iff/my-cluster-kafka): reconciled
2023-03-08 09:47:23 INFO  StrimziPodSetController:292 - Reconciliation #18(watch) StrimziPodSet(iff/my-cluster-kafka): StrimziPodSet will be reconciled
2023-03-08 09:47:23 INFO  StrimziPodSetController:328 - Reconciliation #18(watch) StrimziPodSet(iff/my-cluster-kafka): reconciled
2023-03-08 09:47:28 INFO  StrimziPodSetController:292 - Reconciliation #19(watch) StrimziPodSet(iff/my-cluster-kafka): StrimziPodSet will be reconciled
2023-03-08 09:47:28 INFO  StrimziPodSetController:328 - Reconciliation #19(watch) StrimziPodSet(iff/my-cluster-kafka): reconciled
2023-03-08 09:47:28 INFO  StrimziPodSetController:292 - Reconciliation #20(watch) StrimziPodSet(iff/my-cluster-kafka): StrimziPodSet will be reconciled
2023-03-08 09:47:28 INFO  StrimziPodSetController:328 - Reconciliation #20(watch) StrimziPodSet(iff/my-cluster-kafka): reconciled
2023-03-08 09:47:29 INFO  StrimziPodSetController:292 - Reconciliation #21(watch) StrimziPodSet(iff/my-cluster-kafka): StrimziPodSet will be reconciled
2023-03-08 09:47:29 INFO  StrimziPodSetController:328 - Reconciliation #21(watch) StrimziPodSet(iff/my-cluster-kafka): reconciled
2023-03-08 09:47:34 INFO  AbstractOperator:378 - Reconciliation #1(watch) Kafka(iff/my-cluster): Reconciliation is in progress
2023-03-08 09:47:34 INFO  AbstractOperator:378 - Reconciliation #2(watch) KafkaConnect(iff/kafka-connect): Reconciliation is in progress
2023-03-08 09:48:09 INFO  ClusterOperator:120 - Triggering periodic reconciliation for namespace iff
2023-03-08 09:48:10 INFO  StrimziPodSetController:292 - Reconciliation #24(watch) StrimziPodSet(iff/my-cluster-kafka): StrimziPodSet will be reconciled
2023-03-08 09:48:10 INFO  StrimziPodSetController:328 - Reconciliation #24(watch) StrimziPodSet(iff/my-cluster-kafka): reconciled
2023-03-08 09:48:34 INFO  AbstractOperator:378 - Reconciliation #1(watch) Kafka(iff/my-cluster): Reconciliation is in progress
2023-03-08 09:48:34 INFO  AbstractOperator:378 - Reconciliation #2(watch) KafkaConnect(iff/kafka-connect): Reconciliation is in progress
2023-03-08 09:48:50 INFO  StrimziPodSetController:292 - Reconciliation #25(watch) StrimziPodSet(iff/my-cluster-kafka): StrimziPodSet will be reconciled
2023-03-08 09:48:50 INFO  StrimziPodSetController:328 - Reconciliation #25(watch) StrimziPodSet(iff/my-cluster-kafka): reconciled
2023-03-08 09:49:30 INFO  StrimziPodSetController:292 - Reconciliation #26(watch) StrimziPodSet(iff/my-cluster-kafka): StrimziPodSet will be reconciled
2023-03-08 09:49:30 INFO  StrimziPodSetController:328 - Reconciliation #26(watch) StrimziPodSet(iff/my-cluster-kafka): reconciled
2023-03-08 09:49:34 INFO  AbstractOperator:378 - Reconciliation #1(watch) Kafka(iff/my-cluster): Reconciliation is in progress
2023-03-08 09:49:34 INFO  AbstractOperator:378 - Reconciliation #2(watch) KafkaConnect(iff/kafka-connect): Reconciliation is in progress
2023-03-08 09:49:35 ERROR Util:153 - Reconciliation #2(watch) KafkaConnect(iff/kafka-connect): Exceeded timeout of 300000ms while waiting for Deployment resource kafka-connect-connect in namespace iff to be ready
2023-03-08 09:49:35 ERROR AbstractOperator:258 - Reconciliation #2(watch) KafkaConnect(iff/kafka-connect): createOrUpdate failed
io.strimzi.operator.common.operator.resource.TimeoutException: Exceeded timeout of 300000ms while waiting for Deployment resource kafka-connect-connect in namespace iff to be ready
        at io.strimzi.operator.common.Util$1.lambda$handle$1(Util.java:154) ~[io.strimzi.operator-common-0.31.1.jar:0.31.1]
        at io.vertx.core.impl.future.FutureImpl$3.onFailure(FutureImpl.java:153) ~[io.vertx.vertx-core-4.2.4.jar:4.2.4]`
```

**Comment by yshashix** [comment]
Increased allocated resources and also updated kafka version to 3.3 and strimzi to 0.32

```
`  resources:
      requests:
        memory: 500Mi
        cpu: 300m
      limits:
        memory: 500Mi
        cpu: 500m
    jvmOptions:
      "-Xmx": "400m"
      "-Xms": "300m"`
```

PR created in DT
